[inet_http_server]
port=127.0.0.1:19001

[supervisord]
nodaemon=true

[include]
files = /etc/supervisord.conf.d/*.conf

[supervisorctl]
serverurl=http://127.0.0.1:19001

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface
